#!/bin/sh
#
# Demo Program starter 
# (currently commented out as it is a bit annoying)

start() {
#        echo "Starting demo..."
#	/usr/bin/chatterbox
}

# Nothing to stop
stop() {
#        echo "Stopping demo..."
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

